/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package university_managment_system_by_nazeer_ahmed;
import javax.swing.JOptionPane;

import java.awt.TextField;

/**
 *
 * @author Nazeer_Ahmed
 */
public class addstudent extends javax.swing.JFrame {

    /**
     * Creates new form addstudent
     */
    public addstudent() {
        initComponents();
        setBounds(300,50,467,650);
         setResizable(false); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        jLabel11.setIcon(new javax.swing.ImageIcon("F:\\IMPORTANT\\COMPUTER SCIENCE\\BS_CS_4\\DBMS\\University_Managment_system_By_Nazeer_Ahmed\\src\\university_managment_system_by_nazeer_ahmed\\Images\\studentpicforadd.jfif")); // NOI18N
        jLabel11.setText("jLabel11");

        jLabel13.setIcon(new javax.swing.ImageIcon("F:\\IMPORTANT\\COMPUTER SCIENCE\\BS_CS_4\\DBMS\\University_Managment_system_By_Nazeer_Ahmed\\src\\university_managment_system_by_nazeer_ahmed\\Images\\studentpicforadd.jfif")); // NOI18N
        jLabel13.setText("jLabel13");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel1.setText(" ADD NEW STUDENT");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 30, 200, 60);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText(" NAME        :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 130, 70, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("FATHER_N :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 180, 70, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("ADDRESS   : ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 230, 70, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("EMAIL        : ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 280, 70, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Roll_No      : ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 330, 70, 20);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(110, 130, 120, 20);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(110, 180, 120, 20);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(110, 230, 120, 20);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(110, 280, 120, 20);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(110, 330, 120, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("DEPT_ID    : ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 380, 70, 14);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("DOB(y-m-d):");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 420, 80, 14);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("CNIC           : ");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 460, 70, 14);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("FSC (%)    :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 500, 70, 14);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BBA", "CS", "BED", "AF", "MATH" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(110, 530, 120, 20);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(110, 380, 120, 20);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(110, 420, 120, 20);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(110, 460, 120, 20);
        getContentPane().add(jTextField9);
        jTextField9.setBounds(110, 500, 120, 20);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 570, 200, 23);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("DEPT          :");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(30, 530, 70, 14);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(10, 0, 73, 23);

        jLabel14.setIcon(new javax.swing.ImageIcon("F:\\IMPORTANT\\COMPUTER SCIENCE\\BS_CS_4\\DBMS\\University_Managment_system_By_Nazeer_Ahmed\\src\\university_managment_system_by_nazeer_ahmed\\Images\\studentpicforadd.jfif")); // NOI18N
        jLabel14.setText("jLabel14");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(0, -6, 470, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            String a=jTextField1.getText();
            String b=jTextField2.getText();
            String c=jTextField3.getText();
            String d=jTextField4.getText();
            int e=Integer.parseInt(jTextField5.getText());
            String f=jTextField6.getText();
            String g=jTextField7.getText();
            String h=jTextField8.getText();
            String i=jTextField9.getText();
            String j=(String)jComboBox1.getSelectedItem();
            try
            {
                connwithmysql cc = new connwithmysql();
                String sql="insert into student values('"+a+"','"+b+"','"+c+"','"+d+"',"+e+",'"+f+"','"+g+"','"+h+"','"+i+"','"+j+"')";
                cc.stmt.executeUpdate(sql);
                JOptionPane.showMessageDialog(null,"DATA INSERT SECCESFULLY ! ");   
                setVisible(true);    
            }
           catch(Exception ex)
            {
                JOptionPane.showMessageDialog(this,ex.getMessage());
            }
             
            
            
            
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    new project().setVisible(true);
                setVisible(false);            // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addstudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
